$schema: https://azuremlschemas.azureedge.net/latest/pipelineJob.schema.json
type: pipeline
display_name: machine_failure_training_pipeline
experiment_name: machine-failure-training
description: Training pipeline to predict machine failure using Decision Tree classifier

inputs:
  raw_data:
    type: uri_file
    path: azureml:used-cars-data@latest

outputs:
  train_data:
    type: uri_folder
  test_data:
    type: uri_folder
  model_info_output_path:
    type: uri_file

settings:
  default_datastore: azureml:workspaceblobstore
  default_compute: azureml:cpu-cluster
  continue_on_step_failure: false

jobs:
  prep_data:
    name: prep_data
    display_name: Prep Data
    code: ../../../data-science/src
    command: >-
      python prep.py  
      --raw_data ${{inputs.raw_data}} 
      --train_data ${{outputs.train_data}}
      --test_data ${{outputs.test_data}} 
    environment: azureml:used-cars-train-env@latest
    inputs:
      raw_data: ${{parent.inputs.raw_data}}
    outputs:
      train_data: ${{parent.outputs.train_data}}
      test_data: ${{parent.outputs.test_data}}

  sweep_step:
    type: sweep
    display_name: sweep-job
    trial:
      type: command
      code: ../../../data-science/src
      command: >-
        python train.py 
        --train_data ${{inputs.train_data}} 
        --test_data ${{inputs.test_data}} 
        --n_estimators ${{inputs.n_estimators}} 
        --max_depth ${{inputs.max_depth}} 
        --model_output ${{outputs.model_output}}
      environment:
        conda_file: mlops/azureml/train/conda_dependencies.yml
        image: mcr.microsoft.com/azureml/openmpi3.1.2-ubuntu18.04
      inputs:
        train_data: ${{parent.jobs.prep_data.outputs.train_data}}
        test_data: ${{parent.jobs.prep_data.outputs.test_data}}
        n_estimators: 10
        max_depth: 3
      outputs:
        model_output: ${{parent.outputs.model_output}}
    sampling_algorithm: random
    search_space:
      n_estimators:
        type: choice
        values: [10, 20, 30, 50]
      max_depth:
        type: choice
        values: [1, 3, 5, 10]
    objective:
      goal: minimize
      primary_metric: MSE
    limits:
      max_total_trials: 20
      max_concurrent_trials: 10
      timeout: 7200

  register_model:
    name: register_model
    display_name: Register Model
    code: ../../../data-science/src
    command: >-
      python register.py 
      --model_name ${{inputs.model_name}} 
      --model_path ${{inputs.model_path}} 
      --model_info_output_path ${{outputs.model_info_output_path}}
    environment: azureml:used-cars-train-env@latest
    inputs:
      model_name: "used_cars_price_prediction_model"
      model_path: ${{parent.jobs.sweep_step.outputs.model_output}}
    outputs:
      model_info_output_path: ${{parent.outputs.model_info_output_path}}
