name: training-env
channels:
  - conda-forge
dependencies:
  - python=3.8
  - pip
  - scikit-learn=0.24.1
  - pandas=1.2.1
  - joblib=1.0.0
  - matplotlib=3.3.3
  - pip:
      - pyarrow==7.0.0         # ⬅ moved to pip section
      - azureml-mlflow==1.38.0
      - azure-ai-ml==1.0.0
